import sys

import shuffles_analizer as an

def main(option, filename, analysis_type=None):
    if option == "analize":
        an.main(analysis_type,filename)
    elif option == "diligent":
        an.main(option,filename)

try:
    analysis_type = None
    if len(sys.argv)>3:
        analysis_type = sys.argv[3]
    main(sys.argv[1],sys.argv[2],analysis_type)
except BaseException as err:
    print(
        f"Usage:\n python3 {sys.argv[0]} <option> <filename> <analysis_type>\n where:\n *<option> can be either 'diligent' or 'analize'\n *<filename> the name of a json file generated by shuffle_generator and present in this same folder.\n *<analysis_type> should be provided only when analizing and can be 'counterexamples', 'essential', 'palindrome', 'equality', 'inequality', 'included', 'primitives'\n"
    )
    print(err)