import sys

import shuffles_analizer as an
import shuffle_generator as gen

try:
    option = sys.argv[1]
    if option == "analize":
        an.main(sys.argv[3],sys.argv[2])
    elif option == "diligent":
        an.main(option,sys.argv[2])
    elif option == "generate":
        gen.main(sys.argv[2],sys.argv[3])

except BaseException as err:
    print(
        f"Usage:\n python3 {sys.argv[0]} analize <filename> <analysis_type> || python3 {sys.argv[0]} diligent <filename> || python3 {sys.argv[0]} generate <alphabet> <N>\n where:"
    )
    print(
        " *<filename> is the name of a json file generated by shuffle_generator and present in this same folder.\n *<analysis_type> can be 'counterexamples', 'essential', 'palindrome', 'equality', 'inequality', 'included', 'primitives'\n"
    )
    print(err)