import json
import sys
import os

import graphviz

import diligent_spliffer as dil

def retrieve_json_data(filename):
        with open(filename,'r') as file:
            json_data = json.load(file)
        return json_data

def build_diligent_spliffers(filename):
    folder_name = filename+"_diligent_spliffers"

    if not os.path.exists(folder_name):
        os.makedirs(folder_name)

    #Esto es horrible, lo hago para encontrar el alfabeto a partir del filename
    #El alfabeto suele venir después del número en el formato de nombres que estoy usando
    #e.g. "shuffle_to_5_ab_counterexamples" o "shuffle_to_3_abcd"
    alph=""
    l = filename.split("_")
    for i in range(len(l)):
        if l[i].isalnum():
            alph = l[i+1]
            break

    json_data = retrieve_json_data(filename)
    for thing in json_data:
        try:
            w1 = thing["w1"]
            w2 = thing["w2"]
            w3 = thing["w3"]
            S = dil.diligent_spliffer(w1,w2,w3,alph)
            new_file = folder_name+"/"+w1+"_"+w2+"_"+w3
            S._A.save(new_file,format="dot") #esto no se hace pero no reimplementé awalipy.save en Spliffer
            S._A.save(new_file+".json",format="json")
            graphviz.render('dot','png',new_file)
            os.remove(new_file)
        except (IndexError,TypeError):
            continue

def find_counterexamples(filename):
    """
    Filters <filename> for all tuples (w1,w2,w3) that have
    been marked with False regarding the commutativity being
    enough to generate all possible ways to shuffle them.

    It dumps the results in '<filename>_counterexamples'.
    """
    filename_counter = filename+"_counterexamples"
    counterexamples = []

    json_data = retrieve_json_data(filename)

    n = len(json_data)

    for thing in json_data:
        if not thing["commuting_is_enough"]:
            counterexamples.append(thing)

    counterexamples.insert(0,str(len(counterexamples))+" counterexamples out of "+str(n)+" tuples.")

    json_str = json.dumps(counterexamples,indent=2)

    with open(filename_counter, 'w') as file:
        file.write(json_str)

def main(option, filename):
    if option == "counterexamples":
        find_counterexamples(filename)
    elif option == "diligent":
        build_diligent_spliffers(filename)
    else:
        raise ValueError

try:
    main(sys.argv[1], sys.argv[2])
except BaseException as err:
    print(
        f"Usage:\n python3 {sys.argv[0]} <option> <filename>\n with:\n *<option> either 'diligent' or 'counterexample'\n *<filename> the name of a json file generated by shuffle_generator and present in this same folder."
    )
    print(
        "If <option> is 'counterexamples' a file called '<filename>+_counterexamples' will be generated with the results."
    )
    print(
        "If <option> is 'diligent' a folder called '<filename>_diligent_spliffers' will be created containing all diligent spliffers associated with the file."
    )
    print(err)