import json
import sys


def main(filename):
    filename_counter = filename+"_counterexamples"
    counterexamples = []

    with open(filename,'r') as file:
        json_data = json.load(file)

    n = len(json_data)

    for thing in json_data:
        if not thing["commuting_is_enough"]:
            counterexamples.append(thing)

    counterexamples.insert(0,str(len(counterexamples))+" counterexamples out of "+str(n)+" tuples.")

    json_str = json.dumps(counterexamples,indent=2)

    with open(filename_counter, 'w') as file:
        file.write(json_str)
        
try:
    main(sys.argv[1])
except:
    print(
        f"Usage:\n python3 {sys.argv[0]} <filename>\n with:\n *<filename> the name of a json file generated by shuffle_generator and present in this same folder."
    )
    print(
        "A file called '<filename>+_counterexamples' will be generated with the results."
    )